/**
 * Cloudflare Email Service — outbound sending (Email Sending, open beta).
 *
 * Sends transactional email from the ai-engineer-roadmap.xyz domain via
 * POST /accounts/{account}/email/sending/send (flat JSON schema).
 *
 * One-time prerequisites (see docs/cloudflare-email.md):
 *  1. Dashboard → Compute → Email Service → Email Sending → Onboard Domain →
 *     ai-engineer-roadmap.xyz → "Add records and onboard". This adds the
 *     DKIM / DMARC / cf-bounce DNS records (key material is generated by
 *     Cloudflare, so this step cannot be scripted).
 *  2. An API token with the "Email Sending" permission. The Email Routing
 *     token in CLOUDFLARE_EMAIL_API_TOKEN does NOT carry Sending scope —
 *     set CLOUDFLARE_EMAIL_SENDING_API_TOKEN to a Sending-scoped token.
 *
 * Inbound routing (contact@ai-engineer-roadmap.xyz → Gmail) is already
 * configured separately via Email Routing; this module is sending-only.
 */

const CF_ACCOUNT_ID = process.env.CLOUDFLARE_ACCOUNT_ID;
const SEND_TOKEN =
  process.env.CLOUDFLARE_EMAIL_SENDING_API_TOKEN ||
  process.env.CLOUDFLARE_EMAIL_API_TOKEN;
const DEFAULT_FROM =
  process.env.EMAIL_FROM ||
  "AI Engineer Roadmap <contact@ai-engineer-roadmap.xyz>";

const API = "https://api.cloudflare.com/client/v4";

export function emailSendingConfigured(): boolean {
  return Boolean(CF_ACCOUNT_ID && SEND_TOKEN);
}

export interface SendEmailInput {
  to: string | string[];
  subject: string;
  html: string;
  text: string;
  /** Overrides EMAIL_FROM. Must be an address on an onboarded sending domain. */
  from?: string;
  replyTo?: string;
}

export interface SendEmailResult {
  id?: string;
  status: number;
}

export async function sendEmail(
  input: SendEmailInput,
): Promise<SendEmailResult> {
  if (!emailSendingConfigured()) {
    throw new Error(
      "Cloudflare Email Sending not configured: set CLOUDFLARE_ACCOUNT_ID and " +
        "CLOUDFLARE_EMAIL_SENDING_API_TOKEN (see docs/cloudflare-email.md)",
    );
  }
  const url = `${API}/accounts/${CF_ACCOUNT_ID}/email/sending/send`;
  const body: Record<string, unknown> = {
    to: input.to,
    from: input.from || DEFAULT_FROM,
    subject: input.subject,
    html: input.html,
    text: input.text,
  };
  if (input.replyTo) body.reply_to = input.replyTo;

  const res = await fetch(url, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${SEND_TOKEN}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify(body),
    cache: "no-store",
  });

  if (!res.ok) {
    const detail = (await res.text()).slice(0, 400);
    let hint = "";
    if (res.status === 401 || res.status === 403 || res.status === 404) {
      hint =
        " — the API token likely lacks the 'Email Sending' permission, or " +
        "ai-engineer-roadmap.xyz has not been onboarded under Compute → " +
        "Email Service → Email Sending. See docs/cloudflare-email.md.";
    }
    throw new Error(`Cloudflare Email send ${res.status}: ${detail}${hint}`);
  }

  let id: string | undefined;
  try {
    const json = (await res.json()) as { result?: { id?: string } };
    id = json.result?.id;
  } catch {
    // An empty / non-JSON 2xx body is acceptable for this endpoint.
  }
  return { id, status: res.status };
}
