// Owner-only (route is guarded by ./layout.tsx). REDACTED inline copy of the
// owner evidence at data/app-prep/_evidence/cortex-portal.md: internal
// @vitrifi.net contact addresses and raw git commit-count statistics /
// commit SHAs are intentionally stripped — qualitative claims only. Inlined
// as a TS module (not read from data/) so the un-redacted source file is
// never the thing that ships, and redaction lives in version control.

export const CORTEX_PORTAL_TITLE = "Vitrifi · Cortex Portal — Deep Dive";

export const CORTEX_PORTAL_BODY = [
  "> Owner-only knowledge source. Qualitative claims only — internal contact",
  "> details and raw git statistics are intentionally omitted here.",
  "",
  "## The project",
  "",
  "**Cortex Portal** (Vitrifi) — an enterprise platform for **regulated UK fibre /",
  "broadband telecom infrastructure**: order/provisioning management, subscriber &",
  "tenant administration, network-activator field operations, a self-serve customer",
  "portal, and a service marketplace, integrating external carriers (e.g.",
  "CityFibre, OpenReach).",
  "",
  "It is a **monorepo** (Turbo + pnpm workspaces): Go microservices, React web",
  "apps (portal, network-activator), shared TypeScript packages (ui / hooks /",
  "validations / utils), shared Go libs, Temporal task workers, and schema",
  "definitions (GraphQL / OpenAPI / proto). It runs in a regulated environment",
  "where data correctness, auditability, RBAC, and multi-tenancy are first-order",
  "requirements — structurally the same shape as a supervisory data cockpit.",
  "",
  "## My role & scale",
  "",
  "- **Lead contributor** to the platform over the active span",
  "  **Mar 2022 → Dec 2025** (~3.7 years) — well ahead of the next contributor.",
  "- Full-stack: React/TypeScript frontend **and** Go backend, plus shared",
  "  packages, DB migrations, and CI.",
  "",
  "## Stack",
  "",
  "- **Frontend:** React 18, React Router 7, TypeScript, Rsbuild, Apollo Client",
  "  (GraphQL), React Hook Form + Zod, Ant Design, Emotion, TanStack React Table,",
  "  GraphQL Codegen, Playwright (E2E).",
  "- **Backend:** Go (Chi router, GQLGen GraphQL, REST), PostgreSQL via pgx +",
  "  SQLC, MongoDB, golang-migrate, Temporal (workflow orchestration), NATS",
  "  (protobuf messaging), AWS S3 / Cognito / Secrets Manager, OpenTelemetry",
  "  tracing, testify.",
  "- **Infra:** Docker multi-stage builds, GitLab CI, Kubernetes (sealed-secrets,",
  "  Teleport cluster access).",
  "",
  "## Themes",
  "",
  "- **Forms / validation framework migration.** Led the move of all portal",
  "  forms to Zod v4 with a custom resolver handling null/undefined globally,",
  "  including the resolvers v5 upgrade, letting types infer from the schema.",
  "- **Custom hook architecture.** Built a centralised form-error handler",
  "  bridging Apollo GraphQL error extensions, field-level form errors, and",
  "  i18n notifications; refactored database forms onto it.",
  "- **Backend-side query performance for large tables.** Moved",
  "  search/sort/filter/aggregation out of the browser into SQL so large",
  "  reporting/event tables stay responsive — including a NULLIF-based",
  "  empty-parameter optimisation, with tests.",
  "- **RBAC / multi-tenancy / auth.** Permission seed data per role; extracted",
  "  Cognito user-pool matching into a reusable AWS helper package with tests.",
  "- **Testing discipline.** Added unit tests reaching full coverage on several",
  "  Go packages; fixed testifylint correctness; contributed Go",
  "  integration/fuzz and Playwright E2E coverage.",
  "- **TypeScript strictness.** Replaced explicit `any` across the codebase and",
  "  fixed the resulting type errors.",
  "- **Architecture / maintainability.** Drove the component-collocation",
  "  pattern — feature-scoped components over generic catch-all folders — and",
  "  DB schema evolution via golang-migrate.",
  "",
  "## ECB requirement → cortex-portal proof",
  "",
  "| ECB JD asks | Cortex Portal proof |",
  "|---|---|",
  "| Data-intensive dashboard in a **regulated** environment, audit trails | Regulated UK-fibre telecom ops portal; lead contributor; reporting/event tables, audited provisioning flows, golang-migrate schema evolution |",
  "| React 18 + TypeScript; visualisation/reporting modules | React 18 + TS, TanStack React Table for dense reporting grids, Apollo cache as the data layer |",
  "| Redux Toolkit / D3.js | **Transferable, not direct** — normalised client state via Apollo cache + selectors; data-grid rendering via TanStack Table |",
  "| REST API backend (Python FastAPI / Java Spring Boot) | **Transferable, not direct** — Go GraphQL (GQLGen) + REST (Chi); same concerns: validation, pagination, structured errors, codegen contracts |",
  "| SQL (PostgreSQL/Oracle) + ETL | PostgreSQL via pgx/SQLC, golang-migrate; NATS event pipelines + Temporal workflows ≈ long-running ingest/ETL orchestration |",
  "| OAuth2 / SAML / RBAC in enterprise env | Multi-tenant RBAC with per-role permission model; AWS Cognito; sealed-secrets |",
  "| Large-dataset query performance | Search/sort/filter/aggregation pushed to SQL incl. NULLIF optimisation |",
  "| Testing pyramid (Jest/Cypress/pytest) | Playwright E2E + Go testify unit/integration + fuzz; full-coverage initiatives |",
  "| Docker / Kubernetes / GitLab CI | **Direct match** — Docker multi-stage, GitLab CI, Kubernetes (sealed-secrets, Teleport) |",
  "| Banking regulation domain (Basel/CRR) | **No direct domain** — frame as proven fast ramp-up into a regulated, audited domain (telecom regulatory) |",
  "",
  "## Honest gaps (do not bluff)",
  "",
  "- **D3.js / Redux Toolkit:** no production D3; state is Apollo-cache-based,",
  "  not Redux. Bridge: dense data grids (TanStack Table), normalised client",
  "  cache + memoised selectors, render-perf discipline — directly",
  "  transferable, learn the specific libs fast.",
  "- **Python / Java backend:** backend experience is Go. Bridge: same API",
  "  concerns (schema-first contracts, validation, pagination, structured",
  "  errors, auth middleware) — FastAPI/Spring is a syntax delta, not a",
  "  concept delta.",
  "- **Banking/supervisory domain:** none. Bridge: demonstrated",
  "  regulated-domain ramp-up in telecom; structured approach to learning a",
  "  domain from experts.",
].join("\n");
