import { headers } from "next/headers";
import { redirect } from "next/navigation";
import { auth } from "@/lib/auth";
import { isOwner } from "@/lib/owner";
import { getAppPrepSeed } from "@/lib/app-prep-seed";

// Owner-only guard for interview prep (covers prep + prep/memorize), with a
// public exception for slugs that ship a committed static prep artifact
// (data/app-prep/<slug>.json, generated by the Rust `gen-app-prep` bin).
export default async function ApplicationPrepLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ id: string }>;
}) {
  const [session, { id }] = await Promise.all([
    auth.api.getSession({ headers: await headers() }),
    params,
  ]);
  if (!isOwner(session) && !getAppPrepSeed(id)) redirect("/");
  return <>{children}</>;
}
